
services:
  backend:
    container_name: backend
    build:
      dockerfile: packages/backend/Dockerfile
      context: .
      target: dev
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./packages/backend/:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - db
    ports:
      - "3170:3170"

  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
